### ISSUE TITLE
CancellationToken hangs all subsequent requests 

### ISSUE THREAD

**Issue by cbrammer** [paulcbetts/Fusillade#20]
First off, thanks for the repo. Great work.

I have run across what I believe to be a fairly serious bug. Anytime `Cancel` is called on a `CancellationTokenSouce` all subsequent requests hang. I have created a simple test case that exhibits this: https://gist.github.com/cbrammer/0505f733422c60ddc6fbd9755e62b70b
1. Could you verify that this is actually a bug and not something that I am overlooking?
2. Fix it please :)

**Comment by cbrammer** [comment]
Friendly ping on if this has been received

**Comment by ghuntley** [comment]
@cbrammer this is resolved in the release that just went out.

See https://github.com/paulcbetts/Fusillade/releases/tag/0.7.0 for release notes.

**Comment by cbrammer** [comment]
!!! Thank you

**Comment by Mabion** [comment]
hello, we are having the same problem with the cancellationtokens. When running the unittests @cbrammer has created we see the test still fails on v0.7.0. 

Could you please take a look a this again?

**Comment by ghuntley** [comment]
@justinimel @Mabion can you please raise a PR.
